services:
  iconttv-discord-hook:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: iconttv-discord-hook
    shm_size: '512m'
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    user: 1000:1000
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
  
  iconttv-discord-hook-archive:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: iconttv-discord-hook-archive
    shm_size: '512m'
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    user: 1000:1000
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ./logs/archive:/app/logs
    restart: unless-stopped
