CREATE TABLE IF NOT EXISTS MESSAGE (
  CHANNEL_ID INTEGER PRIMARY KEY,
  GUILD_ID INTEGER PRIMARY KEY,
  MESSAGE_ID INTEGER PRIMARY KEY,
  MESSAGE_TYPE INTEGER NOT NULL,
  MESSAGE TEXT NOT NULL,
  SENDER_ID INTEGER NOT NULL,
  SENDER_NAME TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

